# Generated by Django 3.1.2 on 2020-10-23 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mebsuta_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='total',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='annotation',
            name='Cell_Image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='annotation', to='mebsuta_api.cell_image'),
        ),
    ]
