# Generated by Django 3.1.2 on 2020-10-23 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mebsuta_api', '0002_auto_20201023_1551'),
    ]

    operations = [
        migrations.RenameField(
            model_name='library',
            old_name='total',
            new_name='num_annotated',
        ),
        migrations.AddField(
            model_name='library',
            name='num_cells',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
