# Generated by Django 3.1.2 on 2020-10-26 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mebsuta_api', '0003_auto_20201023_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='cell_image',
            name='annotation',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='cell_image',
            name='isDebris',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='Cell_Image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rel_annotation', to='mebsuta_api.cell_image'),
        ),
        migrations.AlterField(
            model_name='debris',
            name='Cell_Image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debris', to='mebsuta_api.cell_image'),
        ),
    ]
